name: Remove Test Environment
on:
  pull_request:
    branches:
      - main
    types: [closed]
jobs:
  delete-infra:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'us-east-1'
    steps:
      - uses: actions/checkout@master
      - run: echo "::set-env name=BRANCH_NAME::${{ github.head_ref }}"
      - run: terraform init
      - run: terraform destroy -var="branch_name=$BRANCH_NAME" -auto-approve
